name: Minify and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Specify your preferred Node.js version

    - name: Install dependencies
      run: |
        npm install uglifyjs-folder cssnano postcss postcss-cli html-minifier

    - name: Minify HTML, CSS, and JS
      run: |
        # Replace these commands with your actual minification commands
        # Example commands using html-minifier, cssnano, and uglify-js
        npx html-minifier --input-dir ./src --output-dir ./dist --file-ext html
        npx postcss src/*.css --base src --dir dist
        npx uglifyjs-folder src -eo dist -x .js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./dist
